# Generated by Django 4.1.3 on 2022-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0002_alter_gimnasio_fotogym_alter_user_fotous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimnasio',
            name='fotoGym',
            field=models.ImageField(blank=True, height_field=300, upload_to='fotgym', verbose_name='Foto del Gimnasio', width_field=300),
        ),
    ]
