# Generated by Django 4.1.3 on 2022-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0003_alter_gimnasio_fotogym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimnasio',
            name='fotoGym',
            field=models.ImageField(blank=True, upload_to='fotgym', verbose_name='Foto del Gimnasio'),
        ),
    ]
