# Generated by Django 4.1.3 on 2022-12-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0004_alter_gimnasio_fotogym'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ocupados',
            field=models.ManyToManyField(blank=True, to='Pyex_app.unidad'),
        ),
    ]
