# Generated by Django 4.1.3 on 2023-01-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0005_user_ocupados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='estadoUn',
        ),
        migrations.AddField(
            model_name='unidad',
            name='descUn',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='personaUn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
