# Generated by Django 4.1.3 on 2023-01-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0006_remove_unidad_estadoun_unidad_descun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='personaUn',
            field=models.CharField(blank=True, default='nadie', max_length=15, null=True),
        ),
    ]
