# Generated by Django 4.1.3 on 2023-01-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
