# Generated by Django 4.1.3 on 2022-12-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimnasio',
            name='fotoGym',
            field=models.ImageField(blank=True, upload_to='fotgym', verbose_name='Foto del Gimnasio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fotoUs',
            field=models.ImageField(blank=True, upload_to='fotus', verbose_name='Foto de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarjetaUs',
            field=models.ImageField(blank=True, upload_to='fotus', verbose_name='Tarjeta QR'),
        ),
    ]
