# Generated by Django 4.1.2 on 2022-10-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('codGym', models.IntegerField(primary_key=True, serialize=False)),
                ('nomGym', models.CharField(max_length=50)),
                ('direccionGym', models.CharField(max_length=200)),
                ('telefonoGym', models.CharField(max_length=9)),
                ('correoGym', models.CharField(max_length=50)),
                ('fotoGym', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codUs', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sexUs', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NB', 'No binario')], max_length=3)),
                ('fechanacUs', models.DateField()),
                ('telefonoUs', models.CharField(max_length=9)),
                ('fotoUs', models.ImageField(upload_to=None)),
                ('pagoUs', models.BooleanField()),
                ('tarjetaUs', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('codUn', models.IntegerField(primary_key=True, serialize=False)),
                ('nomUn', models.CharField(max_length=50)),
                ('estadoUn', models.BooleanField()),
                ('gimnasioUn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gimnasio')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codCur', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCur', models.CharField(max_length=50)),
                ('profesorCur', models.CharField(max_length=50)),
                ('horarioCur', models.CharField(max_length=50)),
                ('grupoCur', models.CharField(max_length=50)),
                ('descCur', models.CharField(max_length=200)),
                ('capCur', models.IntegerField()),
                ('capMaxCur', models.CharField(max_length=2)),
                ('gimnasioCur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gimnasio')),
            ],
        ),
        migrations.CreateModel(
            name='Apuntado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoAp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.curso')),
                ('usuarioAp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimnasioAl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gimnasio')),
                ('usuarioAl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
            ],
        ),
    ]
