# Generated by Django 4.1.2 on 2022-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horarioCur',
            field=models.TimeField(max_length=50),
        ),
    ]
