# Generated by Django 4.1.2 on 2022-10-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fechanacUs',
            field=models.DateField(null=True),
        ),
    ]
